### PR TITLE
Added a note about the callback functions

### PR DESCRIPTION
**Pull request by jrast**
Added a short section about the callback functions, based on the answers to issue #35 and #36

### CODE REVIEW

**Comment by jrast** [comment]
Feel free to accept or discard this PR. It might help some other devs to understand what the callback functions should do.

**Comment by geky** [comment]
This is great! Mind if I move it below to the "other notes" section?

**Comment by jrast** [comment]
No Prob. Move it where ever it fits best!

**Comment by geky** [comment]
Thanks for this!

**Comment by geky** [comment]
Hi @jrast, we're looking at changing the license to BSD for better compatibility with GPL v2 (https://github.com/ARMmbed/littlefs/issues/59)

Since you're a contributor, would you be able to let us know if it's ok for us to relicense your contributions? You should have an email about this from your commit email, let me know if you didn't get it.

**Pull request merged**
